export const CREATE_TASK = "CREATE_TASK";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const LOAD_TASKS_SUCCESS = "LOAD_TASKS_SUCCESS";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";



export const DELETE_TASK_OPTIMISTIC = "DELETE_TASK_OPTIMISTIC";
